// Banque de questions — QCM style examen OP001 (HEP Vaud)
// Format : 4 propositions (1-4) + "A" (Aucune) + "T" (Toutes).
// Phrases originales, jamais tirées des examens réels ni du catalogue analysé.
//
// Calibrage (v4) — DIFFICULTÉ RELEVÉE, sur retour utilisateur (« trop simple ») :
//   • PIÈGES CONTRE-INTUITIFS : la réponse « évidente » à l'oreille est fausse
//     (après que + indicatif, faire/se voir + infinitif invariable, « en » COD
//     invariable, monter transitif vs intransitif, ne pas penser que + subj...) ;
//   • DISTRACTEURS TRÈS PROCHES : formes quasi jumelles qui exigent une analyse,
//     pas un simple repérage d'intrus ;
//   • « Aucune » / « Toutes » réparties comme dans le réel (~17 %) ;
//   • chaque question porte `why` (raison par option) et a passé une validation
//     indépendante (résolution à l'aveugle, unicité de la réponse).

const RULES = [
  { id: 'orthographe', label: 'Orthographe lexicale & homophones', desc: 'quant/quand, censé/sensé, quoique/quoi que, prêt/près, davantage...' },
  { id: 'modes', label: 'Concordance des modes', desc: 'Subjonctif/indicatif : déclencheurs trompeurs (après que, espérer, ne pas penser...)' },
  { id: 'participe', label: 'Accord du participe passé', desc: 'Pronominaux, faire/se voir + infinitif, « en » COD, monter transitif/intransitif' },
  { id: 'relatifs', label: 'Pronoms relatifs', desc: 'duquel après locution, à qui/en qui, dont abusif, reconstitution' },
  { id: 'pronoms', label: 'Pronoms compléments & sujet implicite', desc: 'y/en, le neutre invariable, ordre des pronoms, participiales détachées' },
];

const AUCUNE = { key: 'A', text: 'Aucune' };
const TOUTES = { key: 'T', text: 'Toutes' };

const QUESTIONS = [
  // ===================== ORTHOGRAPHE =====================
  {
    id: 'orth-1', rule: 'orthographe', type: 'blank',
    stem: "___ à moi, je réserve mon avis ___ le comité aura statué.",
    options: [
      { key: '1', text: 'Quand / quand' },
      { key: '2', text: 'Quant / quand' },
      { key: '3', text: "Qu'en / quand" },
      { key: '4', text: 'Quant / quant' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« Quant à moi » = en ce qui me concerne (locution « quant à ») ; « quand le comité aura statué » = valeur temporelle.",
    why: {
      '1': "« Quand à moi » est une faute fréquente : il faut « Quant à ».",
      '2': "Correct : « Quant à moi » (locution) + « quand » (temps).",
      '3': "« Qu'en à moi » n'existe pas.",
      '4': "2e « quant » fautif : « quant » ne s'emploie qu'avec « à ».",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'orth-2', rule: 'orthographe', type: 'blank',
    stem: "Je ___ ai rendu ___ copies annotées après la correction.",
    options: [
      { key: '1', text: 'leurs / leurs' },
      { key: '2', text: 'leur / leur' },
      { key: '3', text: 'leur / leurs' },
      { key: '4', text: 'leurs / leur' },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« leur » pronom personnel (= à eux) est TOUJOURS invariable ; « leurs copies » est le déterminant possessif, accordé au pluriel.",
    why: {
      '1': "« leurs ai rendu » fautif : le pronom « leur » ne prend jamais de « s ».",
      '2': "« leur copies » fautif : le déterminant s'accorde → « leurs copies ».",
      '3': "Correct : pronom « leur » (invariable) + déterminant « leurs » (pluriel).",
      '4': "Les deux inversés.",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'orth-3', rule: 'orthographe', type: 'blank',
    stem: "Elle est ___ à partir, d'autant qu'elle habite tout ___ de la gare.",
    options: [
      { key: '1', text: 'près / prêt' },
      { key: '2', text: 'prête / près' },
      { key: '3', text: 'prêt / près' },
      { key: '4', text: 'prête / prêt' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« prête à partir » (adjectif « prêt » accordé au féminin) ; « tout près de la gare » (proximité, invariable).",
    why: {
      '1': "Inversé, et « prêt » non accordé au féminin.",
      '2': "Correct : « prête » (adjectif féminin) + « près de » (proximité).",
      '3': "« prêt » non accordé (sujet féminin « elle »).",
      '4': "« prêt » fautif : pour la proximité, c'est « près ».",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'orth-4', rule: 'orthographe', type: 'blank',
    stem: "Chacun est ___ connaître la consigne ; sa réaction n'était donc pas très ___.",
    options: [
      { key: '1', text: 'sensé / censée' },
      { key: '2', text: 'censé / sensée' },
      { key: '3', text: 'censé / censée' },
      { key: '4', text: 'sensé / sensée' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« censé » = supposé, tenu de (être censé faire) ; « sensée » = raisonnable, accordé avec « réaction » (féminin).",
    why: {
      '1': "Inversé : « sensé connaître » et « censée » (raisonnable) sont faux ici.",
      '2': "Correct : « censé » (supposé) + « sensée » (raisonnable, féminin).",
      '3': "2e « censée » fautif : ici le sens est « raisonnable » → sensée.",
      '4': "1er « sensé » fautif : « être censé » = être supposé.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'orth-5', rule: 'orthographe', type: 'blank',
    stem: "___ soient les résultats du vote, nous appliquerons la décision.",
    options: [
      { key: '1', text: 'Quelque' },
      { key: '2', text: 'Quelques' },
      { key: '3', text: 'Quelle que' },
      { key: '4', text: 'Quel que' },
      AUCUNE, TOUTES,
    ],
    answer: 'A',
    explanation: "Devant le verbe « être » au subjonctif, on écrit « quel que » en deux mots, accordé avec le sujet « les résultats » (masc. plur.) → « Quels que ». Cette forme n'est pas proposée. Réponse : Aucune.",
    why: {
      '1': "« Quelque » (invariable) s'emploie devant un nom, pas devant « soient ».",
      '2': "« Quelques » = déterminant : ne convient pas devant le verbe.",
      '3': "« Quelle que » = féminin singulier, alors que « résultats » est masc. plur.",
      '4': "« Quel que » = masculin singulier, mais « résultats » est pluriel → « Quels que ».",
      A: "Correct : la forme attendue « Quels que » n'est pas proposée.",
      T: "Aucune forme proposée n'est correcte.",
    },
  },
  {
    id: 'orth-6', rule: 'orthographe', type: 'blank',
    stem: "Il réclame ___ de temps, persuadé d'en tirer ___ à long terme.",
    options: [
      { key: '1', text: "d'avantage / davantage" },
      { key: '2', text: 'davantage / davantage' },
      { key: '3', text: "davantage / d'avantages" },
      { key: '4', text: "d'avantage / d'avantages" },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« davantage » = adverbe (= plus) : « davantage de temps ». « d'avantages » = nom (bénéfices) : « en tirer des avantages ».",
    why: {
      '1': "1er « d'avantage » fautif : ici « plus de temps » → adverbe « davantage ».",
      '2': "2e « davantage » discutable : « en tirer des avantages » appelle le nom « d'avantages ».",
      '3': "Correct : adverbe « davantage » (de temps) + nom « d'avantages » (à en tirer).",
      '4': "1er « d'avantage » fautif : il faut l'adverbe « davantage ».",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'orth-7', rule: 'orthographe', type: 'blank',
    stem: "___ tu décides, je te soutiendrai, ___ ce ne soit pas la solution la plus simple.",
    options: [
      { key: '1', text: 'Quoique / quoi que' },
      { key: '2', text: 'Quoi que / quoique' },
      { key: '3', text: 'Quoi que / quoi que' },
      { key: '4', text: 'Quoique / quoique' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« Quoi que tu décides » = quelle que soit la chose (deux mots) ; « quoique ce ne soit pas simple » = bien que (un mot).",
    why: {
      '1': "Inversé : « Quoique tu décides » ≠ « quelle que soit la chose ».",
      '2': "Correct : « Quoi que » (quelle que soit la chose) + « quoique » (bien que).",
      '3': "2e « quoi que » fautif : ici le sens est « bien que » → quoique.",
      '4': "1er « quoique » fautif : il faut « quoi que » (= la chose que).",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'orth-8', rule: 'orthographe', type: 'blank',
    stem: "Elle est rentrée bien ___ que prévu, ou ___ elle n'est jamais partie.",
    options: [
      { key: '1', text: 'plutôt / plus tôt' },
      { key: '2', text: 'plus tôt / plutôt' },
      { key: '3', text: 'plus tôt / plus tôt' },
      { key: '4', text: 'plutôt / plutôt' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« plus tôt » = avant dans le temps (contraire de plus tard) ; « plutôt » = de préférence / au contraire.",
    why: {
      '1': "Inversé : le sens temporel appelle « plus tôt » en premier.",
      '2': "Correct : « plus tôt » (temps) + « plutôt » (au contraire).",
      '3': "2e « plus tôt » fautif : ici « au contraire » → plutôt.",
      '4': "1er « plutôt » fautif : « avant que prévu » → plus tôt.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'orth-9', rule: 'orthographe', type: 'sentences',
    instruction: 'Quelle(s) phrase(s) est/sont correctement orthographiée(s) ?',
    options: [
      { key: '1', text: "Quant à ce dossier, il avance bien." },
      { key: '2', text: "Elle est censée présider la séance." },
      { key: '3', text: "Quoique fatigué, il a tenu à finir." },
      { key: '4', text: "Il en sait plus qu'il ne le paraît." },
      AUCUNE, TOUTES,
    ],
    answer: 'T',
    explanation: "Les quatre sont correctes : « Quant à » (1), « censée » = supposée (2), « Quoique » = bien que + ellipse (3), « ne » explétif + « le » neutre (4). Réponse : Toutes.",
    why: {
      '1': "Correcte : « Quant à » (en ce qui concerne).",
      '2': "Correcte : « censée » (= supposée), accordé au féminin.",
      '3': "Correcte : « Quoique fatigué » (= bien que fatigué).",
      '4': "Correcte : « ne » explétif + « le » neutre invariable.",
      A: "Les quatre phrases sont correctes, donc « Aucune » est faux.",
      T: "Correct : aucune ne contient de faute.",
    },
  },
  {
    id: 'orth-10', rule: 'orthographe', type: 'blank',
    stem: "Le compte rendu ___ clair ___ facile à ___ pour tout le personnel.",
    options: [
      { key: '1', text: 'et / est / lire' },
      { key: '2', text: 'est / et / lire' },
      { key: '3', text: 'est / et / lié' },
      { key: '4', text: 'et / et / lire' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« est » (verbe être) puis « et » (conjonction) puis « lire » (infinitif après « à »). Trois homophones [e] à distinguer par la fonction.",
    why: {
      '1': "« et clair est facile » : le verbe « est » doit venir en premier.",
      '2': "Correct : « est » (verbe) + « et » (conjonction) + « lire » (infinitif).",
      '3': "« lié » (participe) fautif : après « à » il faut l'infinitif « lire ».",
      '4': "« et clair et facile » : il manque le verbe « est ».",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },

  // ===================== MODES (subjonctif / indicatif) =====================
  {
    id: 'mode-1', rule: 'modes', type: 'blank',
    stem: "Je ne pense pas qu'il ___ conscient du risque, mais je sais qu'il ___ de bonne foi.",
    options: [
      { key: '1', text: 'est / est' },
      { key: '2', text: 'soit / soit' },
      { key: '3', text: 'soit / est' },
      { key: '4', text: 'est / soit' },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« penser que » à la forme NÉGATIVE entraîne le subjonctif (« soit ») ; « savoir que » (certitude) garde l'indicatif (« est »).",
    why: {
      '1': "1er « est » fautif : à la forme négative, « ne pas penser que » → subjonctif.",
      '2': "2e « soit » fautif : « savoir que » (certitude) → indicatif.",
      '3': "Correct : subjonctif (ne pas penser que) + indicatif (savoir que).",
      '4': "Les deux inversés.",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'mode-2', rule: 'modes', type: 'blank',
    stem: "Une fois que les chiffres ___ publiés et après qu'ils ___ analysés, on tranchera.",
    options: [
      { key: '1', text: 'seront / aient été' },
      { key: '2', text: 'soient / aient été' },
      { key: '3', text: 'seront / auront été' },
      { key: '4', text: 'soient / auront été' },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« une fois que » et « après que » se construisent tous deux avec l'INDICATIF (futur / futur antérieur), contrairement à l'usage courant qui met à tort le subjonctif après « après que ».",
    why: {
      '1': "2e « aient été » fautif : « après que » → indicatif, pas subjonctif.",
      '2': "Les deux au subjonctif : « une fois que » et « après que » exigent l'indicatif.",
      '3': "Correct : « seront » (indicatif futur) + « auront été » (futur antérieur).",
      '4': "1er « soient » fautif : « une fois que » → indicatif.",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'mode-3', rule: 'modes', type: 'blank',
    stem: "J'espère qu'il ___ à temps, bien qu'il ___ souvent en retard ces derniers mois.",
    options: [
      { key: '1', text: 'arrive / est' },
      { key: '2', text: 'arrivera / soit' },
      { key: '3', text: 'arrive / soit' },
      { key: '4', text: 'arrivera / est' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« espérer que » se construit avec l'INDICATIF (« arrivera »), et non le subjonctif ; « bien que » impose le subjonctif (« soit »).",
    why: {
      '1': "« arrive » ne marque pas le futur attendu ; « est » fautif après « bien que ».",
      '2': "Correct : « espérer que » → indicatif futur ; « bien que » → subjonctif.",
      '3': "1er « arrive » : « espérer » n'entraîne pas le subjonctif, et le futur est attendu.",
      '4': "2e « est » fautif : « bien que » exige le subjonctif « soit ».",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'mode-4', rule: 'modes', type: 'blank',
    stem: "Il me semble qu'elle ___ raison, mais il semble qu'on n'y ___ plus rien changer.",
    options: [
      { key: '1', text: 'ait / puisse' },
      { key: '2', text: 'a / puisse' },
      { key: '3', text: 'a / peut' },
      { key: '4', text: 'ait / peut' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« il me semble que » (avec pronom) exprime une opinion tenue pour vraie → INDICATIF (« a ») ; « il semble que » (sans pronom) → SUBJONCTIF (« puisse »).",
    why: {
      '1': "1er « ait » fautif : « il me semble que » → indicatif.",
      '2': "Correct : « il me semble que » → indicatif ; « il semble que » → subjonctif.",
      '3': "2e « peut » fautif : « il semble que » (sans pronom) → subjonctif.",
      '4': "Les deux inversés.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'mode-5', rule: 'modes', type: 'blank',
    stem: "Réglons ce point avant qu'il ne ___ trop tard pour revenir en arrière.",
    options: [
      { key: '1', text: 'est' },
      { key: '2', text: 'sera' },
      { key: '3', text: 'serait' },
      { key: '4', text: 'était' },
      AUCUNE, TOUTES,
    ],
    answer: 'A',
    explanation: "« avant que » exige le subjonctif : « qu'il ne soit trop tard ». Aucune des formes proposées (indicatif ou conditionnel) ne convient. Réponse : Aucune.",
    why: {
      '1': "« est » = indicatif présent : « avant que » exige le subjonctif.",
      '2': "« sera » = futur : mode fautif.",
      '3': "« serait » = conditionnel : mode fautif.",
      '4': "« était » = imparfait indicatif : mode fautif.",
      A: "Correct : la forme attendue « soit » (subjonctif) n'est pas proposée.",
      T: "Aucune forme proposée ne convient.",
    },
  },
  {
    id: 'mode-6', rule: 'modes', type: 'blank',
    stem: "À moins que le budget ne ___ revu, le projet ___ suspendu dès janvier.",
    options: [
      { key: '1', text: 'est / sera' },
      { key: '2', text: 'soit / soit' },
      { key: '3', text: 'soit / sera' },
      { key: '4', text: 'est / soit' },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« à moins que » impose le subjonctif dans la subordonnée (« soit revu ») ; la principale annonce un fait à venir → indicatif futur (« sera suspendu »).",
    why: {
      '1': "1er « est » fautif : « à moins que » → subjonctif.",
      '2': "2e « soit » fautif : la principale (fait annoncé) est à l'indicatif futur.",
      '3': "Correct : subjonctif (à moins que) + indicatif futur (principale).",
      '4': "Les deux inversés.",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'mode-7', rule: 'modes', type: 'blank',
    stem: "Si nous ___ plus tôt, nous ___ éviter cette erreur coûteuse.",
    options: [
      { key: '1', text: 'aurions réagi / aurions pu' },
      { key: '2', text: 'avions réagi / aurions pu' },
      { key: '3', text: 'avions réagi / avions pu' },
      { key: '4', text: 'aurions réagi / avions pu' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "Irréel du passé : « si » + plus-que-parfait (« avions réagi ») dans la subordonnée — jamais de conditionnel après « si » — et conditionnel passé (« aurions pu ») dans la principale.",
    why: {
      '1': "Conditionnel après « si » interdit (« aurions réagi »).",
      '2': "Correct : « si » + plus-que-parfait, principale au conditionnel passé.",
      '3': "Principale « avions pu » fautive : il faut le conditionnel passé « aurions pu ».",
      '4': "Double faute (conditionnel après « si » + indicatif en principale).",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'mode-8', rule: 'modes', type: 'blank',
    stem: "Il avait promis qu'il ___ nous aider dès qu'il ___ un moment de libre.",
    options: [
      { key: '1', text: 'viendrait / aurait' },
      { key: '2', text: 'viendra / aura' },
      { key: '3', text: 'viendrait / aura' },
      { key: '4', text: 'viendra / aurait' },
      AUCUNE, TOUTES,
    ],
    answer: '1',
    explanation: "Après un verbe introducteur au passé (« avait promis »), le futur devient conditionnel (« viendrait ») ; par concordance, « dès qu'il aurait un moment » passe aussi au conditionnel.",
    why: {
      '1': "Correct : futur dans le passé « viendrait » + concordance « aurait ».",
      '2': "Futur simple fautif après un introducteur au passé.",
      '3': "2e « aura » fautif : la concordance impose « aurait ».",
      '4': "1er « viendra » fautif : futur dans le passé → « viendrait ».",
      A: "L'option 1 est correcte.",
      T: "Les options 2, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'mode-9', rule: 'modes', type: 'sentences',
    instruction: 'Quelle(s) phrase(s) respecte(nt) le mode attendu ?',
    options: [
      { key: '1', text: "Je doute qu'il vienne à la séance." },
      { key: '2', text: "Après qu'il a terminé, il est parti." },
      { key: '3', text: "J'espère qu'il réussira son examen." },
      { key: '4', text: "Bien qu'elle soit prudente, elle a hésité." },
      AUCUNE, TOUTES,
    ],
    answer: 'T',
    explanation: "Toutes correctes : « douter que » → subjonctif (1) ; « après que » → INDICATIF (2, contre-intuitif) ; « espérer que » → indicatif (3) ; « bien que » → subjonctif (4). Réponse : Toutes.",
    why: {
      '1': "Correcte : « douter que » → subjonctif « vienne ».",
      '2': "Correcte : « après que » → indicatif « a terminé » (et non « ait »).",
      '3': "Correcte : « espérer que » → indicatif « réussira ».",
      '4': "Correcte : « bien que » → subjonctif « soit ».",
      A: "Les quatre respectent le mode, donc « Aucune » est faux.",
      T: "Correct : toutes les phrases sont correctes.",
    },
  },
  {
    id: 'mode-10', rule: 'modes', type: 'blank',
    stem: "Il est important que chacun ___ présent, mais il est probable que la séance ___ longue.",
    options: [
      { key: '1', text: 'est / soit' },
      { key: '2', text: 'soit / sera' },
      { key: '3', text: 'soit / soit' },
      { key: '4', text: 'est / sera' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« il est important que » (nécessité) → subjonctif (« soit ») ; « il est probable que » (forte probabilité, ≈ certitude) → INDICATIF (« sera »), à la différence de « il est possible que » (subjonctif).",
    why: {
      '1': "1er « est » fautif : « il est important que » → subjonctif.",
      '2': "Correct : subjonctif (important que) + indicatif (probable que).",
      '3': "2e « soit » fautif : « il est probable que » → indicatif.",
      '4': "1er « est » fautif : « important que » → subjonctif.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },

  // ===================== ACCORD DU PARTICIPE PASSÉ =====================
  {
    id: 'part-1', rule: 'participe', type: 'blank',
    stem: "Les lettres qu'ils se sont ___ pendant des années ont renforcé leur amitié.",
    options: [
      { key: '1', text: 'écrit' },
      { key: '2', text: 'écrits' },
      { key: '3', text: 'écrites' },
      { key: '4', text: 'écrite' },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« s'écrire des lettres » : « se » est COI (à eux), mais le COD « que » (= les lettres, fém. plur.) est placé AVANT → accord avec ce COD : « écrites ».",
    why: {
      '1': "« écrit » non accordé, alors que le COD « que » (fém. plur.) est antéposé.",
      '2': "« écrits » masculin, alors que « lettres » est féminin.",
      '3': "Correct : accord avec le COD antéposé « que » (= les lettres) → « écrites ».",
      '4': "« écrite » au singulier : « lettres » est pluriel.",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'part-2', rule: 'participe', type: 'blank',
    stem: "La robe qu'elle s'est ___ faire pour l'occasion lui va parfaitement.",
    options: [
      { key: '1', text: 'fait' },
      { key: '2', text: 'faite' },
      { key: '3', text: 'faits' },
      { key: '4', text: 'faites' },
      AUCUNE, TOUTES,
    ],
    answer: '1',
    explanation: "« se faire faire quelque chose » : « faire » suivi d'un infinitif reste TOUJOURS invariable, même quand un COD féminin (« la robe qu' ») précède : « fait ».",
    why: {
      '1': "Correct : « faire » + infinitif est invariable → « fait ».",
      '2': "« faite » : piège du COD féminin antéposé, mais faire + infinitif est invariable.",
      '3': "« faits » : accord fautif (faire + infinitif invariable).",
      '4': "« faites » : accord fautif (faire + infinitif invariable).",
      A: "L'option 1 est correcte.",
      T: "Les options 2, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'part-3', rule: 'participe', type: 'blank',
    stem: "Les caisses qu'elle a ___ au grenier étaient lourdes ; elle est ___ épuisée.",
    options: [
      { key: '1', text: 'monté / monté' },
      { key: '2', text: 'montées / montée' },
      { key: '3', text: 'montées / monté' },
      { key: '4', text: 'monté / montée' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« monter » transitif (monter quelque chose) se conjugue avec avoir → accord avec le COD antéposé « que » (= les caisses) : « montées ». « monter » intransitif (elle est montée) se conjugue avec être → accord avec le sujet : « montée ».",
    why: {
      '1': "Aucun accord : le 1er « monter » a un COD antéposé, le 2e est avec être.",
      '2': "Correct : « montées » (COD antéposé, avoir) + « montée » (sujet, être).",
      '3': "2e « monté » fautif : « elle est montée » s'accorde avec le sujet.",
      '4': "1er « monté » fautif : COD « que » (fém. plur.) antéposé → « montées ».",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'part-4', rule: 'participe', type: 'blank',
    stem: "Des candidatures pertinentes, nous en avons ___ un grand nombre cette année.",
    options: [
      { key: '1', text: 'reçu' },
      { key: '2', text: 'reçues' },
      { key: '3', text: 'reçus' },
      { key: '4', text: 'reçue' },
      AUCUNE, TOUTES,
    ],
    answer: '1',
    explanation: "Lorsque le COD est le pronom « en », le participe passé reste généralement INVARIABLE : « nous en avons reçu ».",
    why: {
      '1': "Correct : COD « en » → participe invariable « reçu ».",
      '2': "« reçues » : piège du féminin pluriel, mais « en » laisse invariable.",
      '3': "« reçus » : accord fautif avec « en ».",
      '4': "« reçue » : accord fautif avec « en ».",
      A: "L'option 1 est correcte.",
      T: "Les options 2, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'part-5', rule: 'participe', type: 'blank',
    stem: "La chance que la vie lui a ___, il l'a saisie sans hésiter.",
    options: [
      { key: '1', text: 'offert' },
      { key: '2', text: 'offerts' },
      { key: '3', text: 'offertes' },
      { key: '4', text: 'offrit' },
      AUCUNE, TOUTES,
    ],
    answer: 'A',
    explanation: "Le COD « que » (= la chance, fém. sing.) est antéposé → accord : « offerte ». Cette forme n'est pas proposée. Réponse : Aucune.",
    why: {
      '1': "« offert » non accordé, alors que le COD fém. sing. est antéposé.",
      '2': "« offerts » masculin pluriel : mauvais genre et nombre.",
      '3': "« offertes » féminin pluriel : « la chance » est au singulier.",
      '4': "« offrit » = passé simple, pas un participe passé.",
      A: "Correct : la forme attendue « offerte » n'est pas proposée.",
      T: "Aucune forme proposée n'est correcte.",
    },
  },
  {
    id: 'part-6', rule: 'participe', type: 'blank',
    stem: "Les trois heures que la réunion a ___ nous ont paru interminables.",
    options: [
      { key: '1', text: 'duré' },
      { key: '2', text: 'durées' },
      { key: '3', text: 'durés' },
      { key: '4', text: 'durée' },
      AUCUNE, TOUTES,
    ],
    answer: '1',
    explanation: "« durer » est intransitif : « trois heures » n'est pas un COD mais un complément de durée. Le participe reste INVARIABLE : « duré ».",
    why: {
      '1': "Correct : « durer » intransitif → « que » n'est pas un COD → invariable.",
      '2': "« durées » : « heures » n'est pas un COD (complément de durée).",
      '3': "« durés » : accord fautif (pas de COD).",
      '4': "« durée » : accord fautif (pas de COD).",
      A: "L'option 1 est correcte.",
      T: "Les options 2, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'part-7', rule: 'participe', type: 'blank',
    stem: "___ les deux annexes, tous les documents demandés ont été signés.",
    options: [
      { key: '1', text: 'Exceptés' },
      { key: '2', text: 'Excepté' },
      { key: '3', text: 'Exceptées' },
      { key: '4', text: 'Exceptée' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "Placé DEVANT le nom, « excepté » (comme « vu », « y compris », « attendu ») joue le rôle d'une préposition et reste INVARIABLE : « Excepté les deux annexes ».",
    why: {
      '1': "« Exceptés » : accord fautif devant le nom (rôle de préposition).",
      '2': "Correct : « excepté » devant le nom est invariable.",
      '3': "« Exceptées » : accord fautif (invariable en tête).",
      '4': "« Exceptée » : accord fautif (invariable en tête).",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'part-8', rule: 'participe', type: 'blank',
    stem: "Les candidates qui s'étaient ___ à l'oral se sont ___ attribuer une bourse.",
    options: [
      { key: '1', text: 'présentées / vues' },
      { key: '2', text: 'présentées / vu' },
      { key: '3', text: 'présenté / vu' },
      { key: '4', text: 'présentées / vue' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« se présenter » (pronominal) → accord avec le sujet : « présentées ». Mais « se voir + infinitif » (se voir attribuer) → « vu » reste INVARIABLE.",
    why: {
      '1': "2e « vues » fautif : « se voir + infinitif » reste invariable.",
      '2': "Correct : « présentées » (pronominal, accord) + « vu » (se voir + infinitif, invariable).",
      '3': "1er « présenté » fautif : accord avec le sujet fém. plur.",
      '4': "2e « vue » fautif : « se voir + infinitif » est invariable.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'part-9', rule: 'participe', type: 'sentences',
    instruction: 'Quelle(s) phrase(s) présente(nt) un accord correct ?',
    options: [
      { key: '1', text: "Les kilomètres qu'il a couru l'ont épuisé." },
      { key: '2', text: "Elle s'est fait mal en tombant." },
      { key: '3', text: "Vu les circonstances, la séance est reportée." },
      { key: '4', text: "Les fleurs qu'il a cueillies ont fané." },
      AUCUNE, TOUTES,
    ],
    answer: 'T',
    explanation: "Toutes correctes : « couru » invariable (distance, pas un COD) (1) ; « se faire mal » → « fait » invariable (2) ; « vu » devant le nom invariable (3) ; COD « que » antéposé → « cueillies » (4). Réponse : Toutes.",
    why: {
      '1': "Correcte : « kilomètres » = distance, pas un COD → « couru » invariable.",
      '2': "Correcte : « se faire mal » → « fait » invariable.",
      '3': "Correcte : « vu » devant le nom est invariable.",
      '4': "Correcte : COD « que » (fém. plur.) antéposé → « cueillies ».",
      A: "Les quatre accords sont corrects, donc « Aucune » est faux.",
      T: "Correct : toutes les phrases sont correctes.",
    },
  },
  {
    id: 'part-10', rule: 'participe', type: 'blank',
    stem: "Les consignes qu'on nous avait ___ de ___ n'ont pas toutes été suivies.",
    options: [
      { key: '1', text: 'demandées / respecter' },
      { key: '2', text: 'demandé / respecter' },
      { key: '3', text: 'demandé / respecté' },
      { key: '4', text: 'demandées / respecté' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "Le COD de « demander » n'est pas « les consignes » mais le groupe « de respecter (les consignes) », placé APRÈS → « demandé » invariable. « respecter » est un infinitif (après « de »).",
    why: {
      '1': "« demandées » : piège du relatif « que », mais le COD réel (l'infinitif) est postposé → invariable.",
      '2': "Correct : « demandé » invariable + infinitif « respecter ».",
      '3': "2e « respecté » fautif : après « de », il faut l'infinitif « respecter ».",
      '4': "Deux fautes (accord indu + participe au lieu de l'infinitif).",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },

  // ===================== PRONOMS RELATIFS =====================
  {
    id: 'rel-1', rule: 'relatifs', type: 'blank',
    stem: "L'entreprise pour le compte ___ elle travaille est basée à Genève.",
    options: [
      { key: '1', text: 'dont' },
      { key: '2', text: 'de laquelle' },
      { key: '3', text: 'duquel' },
      { key: '4', text: 'pour laquelle' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "Après une locution prépositive en « de » (pour le compte de), on emploie le relatif composé accordé au féminin « entreprise » : « de laquelle ». « dont » est impossible après une telle locution.",
    why: {
      '1': "« dont » est impossible après une locution prépositive (« pour le compte de »).",
      '2': "Correct : « pour le compte de laquelle » (relatif composé, féminin).",
      '3': "« duquel » = masculin, alors que « entreprise » est féminin.",
      '4': "« pour laquelle » supprime « le compte de » : la locution n'est plus respectée.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'rel-2', rule: 'relatifs', type: 'blank',
    stem: "C'est la raison ___ il a préféré démissionner sans préavis.",
    options: [
      { key: '1', text: 'dont' },
      { key: '2', text: 'que' },
      { key: '3', text: 'à laquelle' },
      { key: '4', text: 'de laquelle' },
      AUCUNE, TOUTES,
    ],
    answer: 'A',
    explanation: "On dit « la raison POUR laquelle il a démissionné ». La forme correcte « pour laquelle » n'est pas proposée. Réponse : Aucune.",
    why: {
      '1': "« dont » (= de laquelle) ne rend pas le sens « pour laquelle ».",
      '2': "« que » supposerait un verbe transitif direct, ce n'est pas le cas.",
      '3': "« à laquelle » : mauvaise préposition (« pour », pas « à »).",
      '4': "« de laquelle » : mauvaise préposition (« pour », pas « de »).",
      A: "Correct : la forme attendue « pour laquelle » n'est pas proposée.",
      T: "Aucune option chiffrée ne convient.",
    },
  },
  {
    id: 'rel-3', rule: 'relatifs', type: 'blank',
    stem: "La collègue ___ je m'adresse et ___ j'ai toute confiance connaît bien le dossier.",
    options: [
      { key: '1', text: 'à qui / à qui' },
      { key: '2', text: 'dont / en qui' },
      { key: '3', text: 'à qui / en qui' },
      { key: '4', text: 'à qui / dont' },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« s'adresser À quelqu'un » → « à qui » ; « avoir confiance EN quelqu'un » → « en qui ».",
    why: {
      '1': "2e « à qui » fautif : « avoir confiance EN » → en qui.",
      '2': "1er « dont » fautif : « s'adresser à » → à qui.",
      '3': "Correct : « s'adresser à » (à qui) + « avoir confiance en » (en qui).",
      '4': "2e « dont » fautif : « avoir confiance en » → en qui.",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'rel-4', rule: 'relatifs', type: 'blank',
    stem: "Il a interrogé vingt témoins, ___ trois seulement ont accepté de témoigner.",
    options: [
      { key: '1', text: 'que' },
      { key: '2', text: 'dont' },
      { key: '3', text: 'qui' },
      { key: '4', text: 'auxquels' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« dont » exprime ici la valeur partitive (parmi lesquels) : « vingt témoins, dont trois ont accepté ».",
    why: {
      '1': "« que » (COD) ne convient pas ici.",
      '2': "Correct : « dont trois » = parmi lesquels trois (valeur partitive).",
      '3': "« qui » ferait de « trois » le complément, ce qui casse la construction.",
      '4': "« auxquels » suppose un verbe en « à » : ce n'est pas le cas.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'rel-5', rule: 'relatifs', type: 'blank',
    stem: "Le rapport au terme ___ la décision sera prise est encore en rédaction.",
    options: [
      { key: '1', text: 'dont' },
      { key: '2', text: 'duquel' },
      { key: '3', text: 'de laquelle' },
      { key: '4', text: 'auquel' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "Après la locution « au terme de », on emploie le relatif composé accordé au masculin « rapport » : « duquel ». « dont » est impossible après une locution prépositive.",
    why: {
      '1': "« dont » est impossible après une locution prépositive (« au terme de »).",
      '2': "Correct : « au terme duquel » (relatif composé, masculin).",
      '3': "« de laquelle » = féminin, alors que « rapport » est masculin.",
      '4': "« auquel » : mauvaise préposition (« de », pas « à »).",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'rel-6', rule: 'relatifs', type: 'blank',
    stem: "C'est un appui décisif ___ nous n'aurions jamais mené le projet à terme.",
    options: [
      { key: '1', text: 'dont' },
      { key: '2', text: 'sans lequel' },
      { key: '3', text: 'duquel' },
      { key: '4', text: 'que' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "La phrase de base est « sans cet appui, nous n'aurions jamais réussi » → « sans lequel ».",
    why: {
      '1': "« dont » (= de) ne rend pas le sens « sans lequel ».",
      '2': "Correct : reconstitution de « sans cet appui » → « sans lequel ».",
      '3': "« duquel » (= de) : mauvaise préposition.",
      '4': "« que » (COD) ne convient pas ici.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'rel-7', rule: 'relatifs', type: 'sentences',
    instruction: 'Quelle(s) phrase(s) emploie(nt) le bon pronom relatif ?',
    options: [
      { key: '1', text: "L'ami sur qui je compte n'est pas venu." },
      { key: '2', text: "Le pays d'où elle vient est lointain." },
      { key: '3', text: "La cause pour laquelle il se bat est juste." },
      { key: '4', text: "Le livre dont la couverture est déchirée est rare." },
      AUCUNE, TOUTES,
    ],
    answer: 'T',
    explanation: "Toutes correctes : « compter SUR » → sur qui (1) ; « venir DE » → d'où (2) ; « se battre POUR » → pour laquelle (3) ; « dont » possession (la couverture DU livre) (4). Réponse : Toutes.",
    why: {
      '1': "Correcte : « compter sur quelqu'un » → sur qui.",
      '2': "Correcte : « venir de » (lieu) → d'où.",
      '3': "Correcte : « se battre pour » → pour laquelle.",
      '4': "Correcte : « dont » = la couverture DU livre (possession).",
      A: "Les quatre relatifs sont corrects, donc « Aucune » est faux.",
      T: "Correct : toutes les phrases sont correctes.",
    },
  },
  {
    id: 'rel-8', rule: 'relatifs', type: 'blank',
    stem: "Personne ne comprend ___ elle tient tant dans ce vieux projet abandonné.",
    options: [
      { key: '1', text: 'ce que' },
      { key: '2', text: 'ce dont' },
      { key: '3', text: 'ce à quoi' },
      { key: '4', text: 'ce pour quoi' },
      AUCUNE, TOUTES,
    ],
    answer: '3',
    explanation: "« tenir À quelque chose » (y être attaché) → « ce à quoi elle tient ».",
    why: {
      '1': "« ce que » supposerait un verbe sans préposition.",
      '2': "« ce dont » supposerait « de », pas « à ».",
      '3': "Correct : « tenir à quelque chose » → « ce à quoi ».",
      '4': "« ce pour quoi » suppose « pour » : mauvaise préposition.",
      A: "L'option 3 est correcte.",
      T: "Les options 1, 2 et 4 sont fautives.",
    },
  },
  {
    id: 'rel-9', rule: 'relatifs', type: 'blank',
    stem: "Voici les dossiers ___ nous devons nous occuper en priorité cette semaine.",
    options: [
      { key: '1', text: 'que' },
      { key: '2', text: 'dont' },
      { key: '3', text: 'desquels' },
      { key: '4', text: 'auxquels' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« s'occuper DE quelque chose » → « dont ». « desquels » ne s'emploie qu'après une locution prépositive (près de, au sujet de...).",
    why: {
      '1': "« que » supposerait un verbe direct : « s'occuper » se construit avec « de ».",
      '2': "Correct : « s'occuper de » → dont.",
      '3': "« desquels » ne s'emploie qu'après une locution en « de », pas ici.",
      '4': "« auxquels » suppose « à », alors que c'est « de ».",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'rel-10', rule: 'relatifs', type: 'blank',
    stem: "Je me doutais ___ elle finirait par refuser cette proposition.",
    options: [
      { key: '1', text: 'de ce que' },
      { key: '2', text: 'à ce que' },
      { key: '3', text: 'dont' },
      { key: '4', text: 'de quoi' },
      AUCUNE, TOUTES,
    ],
    answer: 'A',
    explanation: "« se douter que » se construit directement avec « que » (je me doutais qu'elle refuserait). Cette forme n'étant pas proposée : réponse Aucune.",
    why: {
      '1': "« de ce que » est lourd et non standard : « se douter que ».",
      '2': "« à ce que » convient à « veiller », pas à « se douter ».",
      '3': "« dont » ne peut pas introduire cette complétive.",
      '4': "« de quoi » ne convient pas devant une proposition complète.",
      A: "Correct : la forme attendue « que » n'est pas proposée.",
      T: "Aucune option chiffrée ne convient.",
    },
  },

  // ===================== PRONOMS COMPLÉMENTS & SUJET IMPLICITE =====================
  {
    id: 'pro-1', rule: 'pronoms', type: 'blank',
    stem: "Ce problème, je m'___ suis attaqué sérieusement, mais je ne ___ suis pas encore sorti.",
    options: [
      { key: '1', text: 'en / y' },
      { key: '2', text: 'y / en' },
      { key: '3', text: 'y / y' },
      { key: '4', text: 'en / en' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« s'attaquer À quelque chose » → « y » ; « se sortir DE quelque chose » → « en » (je ne m'en suis pas sorti).",
    why: {
      '1': "Inversé : « s'attaquer à » → y, « se sortir de » → en.",
      '2': "Correct : « s'attaquer à » (y) + « se sortir de » (en).",
      '3': "2e « y » fautif : « se sortir de » → en.",
      '4': "1er « en » fautif : « s'attaquer à » → y.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-2', rule: 'pronoms', type: 'blank',
    stem: "Ils sont bien plus nombreux qu'on ne ___ dit et plus déterminés qu'on ne ___ pense.",
    options: [
      { key: '1', text: 'les / le' },
      { key: '2', text: 'le / le' },
      { key: '3', text: 'le / les' },
      { key: '4', text: 'les / les' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "Le pronom neutre « le » reprend toute la proposition (le fait qu'ils sont nombreux/déterminés) et reste INVARIABLE, même quand le sujet est « ils » : « qu'on ne le dit », « qu'on ne le pense ».",
    why: {
      '1': "1er « les » fautif : le pronom neutre « le » est invariable.",
      '2': "Correct : « le » neutre invariable dans les deux cas.",
      '3': "2e « les » fautif : le pronom neutre reste « le ».",
      '4': "Les deux au pluriel : le pronom neutre ne s'accorde jamais.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-3', rule: 'pronoms', type: 'blank',
    stem: "Des conseils avisés, ce n'est pas l'envie qui me manque de ___ donner.",
    options: [
      { key: '1', text: 'les leur' },
      { key: '2', text: 'leur en' },
      { key: '3', text: 'en leur' },
      { key: '4', text: 'leur les' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« donner des conseils à eux » : le partitif « en » (des conseils) + le COI « leur ». L'ordre est « leur en donner ».",
    why: {
      '1': "« les leur » : « les » (défini) ne convient pas à « des conseils » (partitif → en).",
      '2': "Correct : « leur en donner » (COI « leur » + partitif « en »).",
      '3': "Mauvais ordre : le COI « leur » vient avant « en ».",
      '4': "« leur les » : mauvais pronom et mauvais ordre.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-4', rule: 'pronoms', type: 'sentences',
    instruction: 'Quelle est la seule phrase correcte (sujet implicite cohérent) ?',
    options: [
      { key: '1', text: "Nommé à ce poste l'an dernier, il a vu ses responsabilités croître." },
      { key: '2', text: "Nommé à ce poste l'an dernier, ses responsabilités ont augmenté." },
      { key: '3', text: "Nommé à ce poste l'an dernier, on lui a confié de nouvelles tâches." },
      { key: '4', text: "Nommé à ce poste l'an dernier, c'est un vrai défi qui l'attendait." },
      AUCUNE, TOUTES,
    ],
    answer: '1',
    explanation: "Le participe « Nommé » doit qualifier le sujet de la principale. Seule la phrase 1 le respecte (« il » est nommé et « il » voit). Ailleurs, ce ne sont ni « ses responsabilités », ni « on », ni « un défi » qui sont nommés.",
    why: {
      '1': "Correcte : « il » est nommé et « il » voit ses responsabilités croître.",
      '2': "« ses responsabilités » ne sont pas nommées : sujet incohérent.",
      '3': "« on » n'est pas le sujet nommé : rupture.",
      '4': "« un défi » n'est pas nommé : rupture.",
      A: "L'option 1 est correcte.",
      T: "Les options 2, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-5', rule: 'pronoms', type: 'blank',
    stem: "Ses propres limites, elle en ___ parfaitement consciente, mais elle refuse d'___ parler.",
    options: [
      { key: '1', text: 'y est / en' },
      { key: '2', text: 'est / en' },
      { key: '3', text: 'est / y' },
      { key: '4', text: 'en est / en' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "« être conscient DE » : le « en » est déjà placé en tête (elle EN est consciente), il ne se répète pas → « elle en est consciente ». « parler DE » → « en » (d'en parler).",
    why: {
      '1': "« y est » fautif : « être conscient de » appelle « en », déjà présent.",
      '2': "Correct : « elle en est consciente » + « d'en parler » (parler de).",
      '3': "2e « y » fautif : « parler de » → en.",
      '4': "« en est » redouble le « en » déjà exprimé en tête de phrase.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-6', rule: 'pronoms', type: 'blank',
    stem: "Ce nouveau rythme de travail, il faudra bien que chacun s'___ habitue.",
    options: [
      { key: '1', text: 'en' },
      { key: '2', text: 'le' },
      { key: '3', text: 'lui' },
      { key: '4', text: 'la' },
      AUCUNE, TOUTES,
    ],
    answer: 'A',
    explanation: "« s'habituer À quelque chose » → le pronom attendu est « y » (chacun s'y habitue), qui n'est pas proposé. Réponse : Aucune.",
    why: {
      '1': "« en » reprend « de », alors qu'il faut « à » → y.",
      '2': "« le » = COD, alors que « s'habituer » se construit avec « à ».",
      '3': "« lui » = COI de personne ; ici le complément est une chose.",
      '4': "« la » = COD féminin : ne convient pas.",
      A: "Correct : le pronom attendu « y » (s'habituer à) n'est pas proposé.",
      T: "Aucun pronom proposé ne convient.",
    },
  },
  {
    id: 'pro-7', rule: 'pronoms', type: 'blank',
    stem: "Des solutions, on ___ a envisagé plusieurs avant de ___ retenir une seule.",
    options: [
      { key: '1', text: 'les / la' },
      { key: '2', text: 'en / en' },
      { key: '3', text: 'y / en' },
      { key: '4', text: 'en / les' },
      AUCUNE, TOUTES,
    ],
    answer: '2',
    explanation: "Avec une quantité (« plusieurs », « une seule »), la reprise se fait avec « en » : « on en a envisagé plusieurs », « avant d'en retenir une seule ».",
    why: {
      '1': "« les » (défini) est incompatible avec la quantité « plusieurs ».",
      '2': "Correct : « en » pour la quantité dans les deux cas.",
      '3': "1er « y » fautif : « envisager » n'appelle pas « à ».",
      '4': "2e « les » fautif : « en retenir une seule » (quantité) → en.",
      A: "L'option 2 est correcte.",
      T: "Les options 1, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-8', rule: 'pronoms', type: 'sentences',
    instruction: 'Quelle est la seule phrase correcte (sujet implicite cohérent) ?',
    options: [
      { key: '1', text: "En signant ce contrat, l'entreprise accepte plusieurs risques." },
      { key: '2', text: "En signant ce contrat, des risques importants sont acceptés." },
      { key: '3', text: "En signant ce contrat, il faut rester très prudent." },
      { key: '4', text: "En signant ce contrat, la plus grande prudence s'impose." },
      AUCUNE, TOUTES,
    ],
    answer: '1',
    explanation: "Le sujet du gérondif « en signant » doit être celui de la principale. Seule la phrase 1 le respecte (« l'entreprise » signe et accepte). Ailleurs, ce ne sont ni « des risques », ni « il », ni « la prudence » qui signent.",
    why: {
      '1': "Correcte : « l'entreprise » signe et accepte les risques.",
      '2': "« des risques » ne signent pas : sujet incohérent.",
      '3': "« il » impersonnel ne signe pas : rupture.",
      '4': "« la prudence » ne signe pas : rupture.",
      A: "L'option 1 est correcte.",
      T: "Les options 2, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-9', rule: 'pronoms', type: 'sentences',
    instruction: 'Quelle est la seule phrase correcte (sans redondance) ?',
    options: [
      { key: '1', text: "Les résultats dont je suis le plus fier sont récents." },
      { key: '2', text: "Les résultats dont j'en suis le plus fier sont récents." },
      { key: '3', text: "Les résultats que je suis le plus fier sont récents." },
      { key: '4', text: "Les résultats dont je suis le plus fier d'eux sont récents." },
      AUCUNE, TOUTES,
    ],
    answer: '1',
    explanation: "« être fier DE » → « dont » suffit. Ajouter « en » (2) ou « d'eux » (4) reprend une deuxième fois le complément (redondance) ; « que » (3) est un mauvais relatif.",
    why: {
      '1': "Correcte : « dont » = de ces résultats (être fier de).",
      '2': "« en » redondant : « dont » exprime déjà « de ».",
      '3': "« que » fautif : « être fier » se construit avec « de » → dont.",
      '4': "« d'eux » redondant avec « dont ».",
      A: "L'option 1 est correcte.",
      T: "Les options 2, 3 et 4 sont fautives.",
    },
  },
  {
    id: 'pro-10', rule: 'pronoms', type: 'sentences',
    instruction: 'Quelle(s) phrase(s) emploie(nt) correctement le(s) pronom(s) ?',
    options: [
      { key: '1', text: "Je m'y suis vite habitué." },
      { key: '2', text: "Il s'en est occupé personnellement." },
      { key: '3', text: "Nous le leur avons clairement dit." },
      { key: '4', text: "Elle est plus forte qu'elle ne le paraît." },
      AUCUNE, TOUTES,
    ],
    answer: 'T',
    explanation: "Toutes correctes : « s'habituer à » → y (1) ; « s'occuper de » → en (2) ; ordre COD « le » + COI « leur » (3) ; « le » neutre invariable (4). Réponse : Toutes.",
    why: {
      '1': "Correcte : « s'habituer à » → y.",
      '2': "Correcte : « s'occuper de » → en.",
      '3': "Correcte : ordre « le leur » (COD + COI).",
      '4': "Correcte : « le » neutre invariable.",
      A: "Les quatre sont correctes, donc « Aucune » est faux.",
      T: "Correct : toutes les phrases sont correctes.",
    },
  },
];

if (typeof module !== 'undefined') {
  module.exports = { RULES, QUESTIONS };
}
